worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        location /health {
            access_log off;    # чтобы healthcheck-запросы не засоряли логи
            return 200 "OK\n";
        }

        location / {
            set $upstream http://proxy_session-service:8081;
            proxy_pass $upstream;                            # Проксирует запросы к микросервисам
            proxy_set_header Host $host;                     # Передает оригинальный заголовок Host от клиента к бэкенд-сервису
        }                                                    # микросервисы часто используют Host для маршрутизации или валидации запросов
    }

    server {
        listen 81;

        location /health {
            access_log off;
            return 200 "OK\n";
        }

        location / {
            set $upstream http://proxy_gateway-service:8087;
            proxy_pass $upstream;
            proxy_set_header Host $host;
        }
    }
}
